### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import json
from collections import Counter
import xml.etree.ElementTree as ET
import folium
import folium.plugins
import branca
import branca.colormap as cm
import param
import panel as pn

### Data Preparation

In [2]:
df = pd.read_parquet("data/map_matched_routes.parquet")
df = df[df.matched == True] # only matched routes
df = df.reset_index()

In [3]:
d=[]
for i in range(len(df)):
    d.append(df.unique_id[i][-10:].split('-')[0]+df.unique_id[i][-10:].split('-')[1]+df.unique_id[i][-10:].split('-')[2])
df['dates'] = d
df['dates'] = pd.to_datetime(df['dates'], format='%Y%m%d')

In [4]:
df['month'] = df['dates'].dt.month
df['year'] = df['dates'].dt.year
df = df.reset_index()
df = df.drop(['level_0', 'index'], axis=1)
df

,unique_id,route,matched,dates,month,year
0,00000bf0-0000-1000-a6a0-5b7d6a617b60_2020-11-30,"[[46.069691, 11.121241], [46.069716, 11.121509...",True,2020-11-30,11,2020
1,00001d90-0000-1000-8b30-5b7d6a617b60_2020-11-30,"[[46.07016, 11.120398], [46.070181, 11.12065],...",True,2020-11-30,11,2020
2,0000210d-0000-1000-8d7d-5b7d6a617b60_2020-11-30,"[[46.067214, 11.126787], [46.067211, 11.126772...",True,2020-11-30,11,2020
3,00000735-0000-1000-9635-5b7d6a617b60_2020-11-30,"[[46.069691, 11.12124], [46.069699, 11.121327]]",True,2020-11-30,11,2020
4,00000e00-0000-1000-9ab0-5b7d6a617b60_2020-11-30,"[[46.069695, 11.121283], [46.069716, 11.121509...",True,2020-11-30,11,2020
...,...,...,...,...,...,...
70416,00000c1f-0000-1000-a6bf-5b7d6a617b60_2022-03-04,"[[46.063361, 11.12368], [46.063356, 11.123623]...",True,2022-03-04,3,2022
70417,830baf6d-455a-4f22-bdd4-9be7b521622d_2022-03-04,"[[46.075298, 11.123749], [46.075298, 11.123749]]",True,2022-03-04,3,2022
70418,0daf00f7-4afb-43c6-8c7f-5e674945192d_2022-03-04,"[[46.075385, 11.123814], [46.075445, 11.123859...",True,2022-03-04,3,2022
70419,00000d44-0000-1000-9a34-5b7d6a617b60_2022-03-04,"[[46.070977, 11.124824], [46.070926, 11.124821...",True,2022-03-04,3,2022
70420,aeabdd1c-484e-4426-8114-518f4e1a29f5_2022-03-04,"[[46.068792, 11.125921], [46.068539, 11.125553...",True,2022-03-04,3,2022

In [5]:
df.groupby(['month','year']).size().reset_index().rename(columns={0:'count'}).sort_values(by=['year', 'month']).reset_index().drop(['index'], axis=1)

    month  year  count
0      11  2020     20
1      12  2020   2310
2       1  2021   1149
3       2  2021   2962
4       3  2021   4862
5       4  2021   4886
6       5  2021   5978
7       6  2021   7112
8       7  2021   6921
9       8  2021   5806
10      9  2021   6216
11     10  2021   7111
12     11  2021   5159
13     12  2021   2797
14      1  2022   2258
15      2  2022   4125
16      3  2022    749

In [15]:
# Valhalla request
edge_ids=[]
ids = df.unique_id.to_list()
for id in range(len(ids)):
    df_temp = df[df.unique_id==ids[id]]
    df_points = pd.DataFrame({'lon':[el[1] for i in df_temp.route for el in i], 'lat':[el[0] for i in df_temp.route for el in i]})

    # request
    meili_coordinates = df_points.to_json(orient='records')
    meili_head = '{"shape":'
    meili_tail = ""","search_radius": 300, "shape_match":"edge_walk", "costing":"bicycle", "format":"osrm"}""" # use 'shape_match' : 'edge_walk'
    meili_request_body = meili_head + meili_coordinates + meili_tail
    url = "http://localhost:8002/trace_attributes" # use /trace_attributes 
    headers = {'Content-type': 'application/json'}
    data = str(meili_request_body)

    r = requests.post(url, data=data, headers=headers)
    
    response_text = json.loads(r.text)

    if r.status_code == 200:
        l=[]
        for i in range(len(response_text['edges'])):
            l.append(response_text['edges'][i]['way_id']) #, response_text['osm_changeset'])

        edge_ids.append(list(set(l)))
    else:
        edge_ids.append([])

In [16]:
df['edge_ids'] = edge_ids
df = df[df['edge_ids'].map(lambda d: len(d)) > 0] # remove rows where edge_ids is empty

In [37]:
df.to_parquet('map_matched_edges_ids.parquet')

In [20]:
c = []
for el in edge_ids:
    c.extend(el)
c = Counter(c)

els = 'id: '
for el in c.keys():
    els = els + str(el) +', '
els = els[:-2] # string of way ids to pass to request coordinates

In [23]:
# Overpass request
url = 'http://localhost:12345/api/interpreter'
data = 'data=way('+str(els)+');out geom;'
r = requests.post(url, data=data)
root = ET.fromstring(r.text)

nodes_coords = []
waysids = []
for child in root:
    if child.tag == 'way':
        waysids.append(int(child.attrib['id']))
        nodes=[]
        for node in child:
            if node.tag == 'nd':
                # print(node.attrib['ref']) # node id
                nodes.append([float(node.attrib['lat']), float(node.attrib['lon'])])
        nodes_coords.append(nodes)

In [28]:
cnt=[]
for id in waysids:
    cnt.append(c[id])

In [29]:
ways = pd.DataFrame({'way_id': waysids, 'route': nodes_coords, 'freq': cnt})
ways

          way_id                                              route  freq
0       22986084  [[46.0666524, 11.1190333], [46.0666403, 11.118...  3521
1       22986312  [[46.0674662, 11.1266008], [46.0675156, 11.126...  2309
2       22986560  [[46.069021, 11.1225351], [46.0693306, 11.1224...  1583
3       23056771  [[46.0969958, 11.1125195], [46.096235, 11.1127...    26
4       23058066  [[46.0838565, 11.1146839], [46.0839814, 11.114...   287
...          ...                                                ...   ...
3621  1059368470  [[46.1051947, 11.1092483], [46.1053035, 11.109...     4
3622  1059368474  [[46.0997827, 11.1128606], [46.099779, 11.1137...     1
3623  1059368478  [[46.1056222, 11.1147083], [46.1058355, 11.114...     2
3624  1059368479  [[46.1061001, 11.115034], [46.105945, 11.11482...     3
3625  1059368480  [[46.1059973, 11.1152039], [46.1060561, 11.115...     3

[3626 rows x 3 columns]

In [34]:
# save ways ids, count, and coordinates as json 
# way_id (keys) :  {coords: [list of lists], count_complessivo: int}
d={}
for i in range(len(waysids)):
    d[waysids[i]] = {}
    d[waysids[i]]['coords'] = nodes_coords[i]
    d[waysids[i]]['count_complessivo'] = cnt[i]

In [35]:
d

{22986084: {'coords': [[46.0666524, 11.1190333],
   [46.0666403, 11.1189185],
   [46.0665558, 11.1180829],
   [46.0665522, 11.118046],
   [46.0665479, 11.1180031],
   [46.066504, 11.1175601],
   [46.0664974, 11.117434]],
  'count_complessivo': 3521},
 22986312: {'coords': [[46.0674662, 11.1266008],
   [46.0675156, 11.1264331],
   [46.0675748, 11.1263186],
   [46.0678665, 11.1257547]],
  'count_complessivo': 2309},
 22986560: {'coords': [[46.069021, 11.1225351],
   [46.0693306, 11.1224874],
   [46.0695838, 11.1225012],
   [46.0698051, 11.1225938],
   [46.0698354, 11.1226063]],
  'count_complessivo': 1583},
 23056771: {'coords': [[46.0969958, 11.1125195],
   [46.096235, 11.1127734],
   [46.0955786, 11.1130632],
   [46.0944013, 11.1137155]],
  'count_complessivo': 26},
 23058066: {'coords': [[46.0838565, 11.1146839],
   [46.0839814, 11.1147368],
   [46.0840528, 11.114791],
   [46.0840863, 11.1148243]],
  'count_complessivo': 287},
 23058125: {'coords': [[46.0903875, 11.1183169],
   [46.0904402, 11.1185174],
   [46.0905089, 11.1187845],
   [46.0905542, 11.1189413],
   [46.0906979, 11.1195116],
   [46.0907583, 11.1197514]],
  'count_complessivo': 183},
 23058701: {'coords': [[46.0652385, 11.1356027],
   [46.0651792, 11.1354971],
   [46.0651338, 11.1354434]],
  'count_complessivo': 19},
 23058856: {'coords': [[46.0711365, 11.1352796],
   [46.0710282, 11.1354218],
   [46.0709723, 11.1355488],
   [46.0709283, 11.1356937],
   [46.0709278, 11.1358668],
   [46.0709615, 11.1359821],
   [46.0710268, 11.1360779],
   [46.0711008, 11.1361519],
   [46.0712101, 11.1362043],
   [46.0713696, 11.1362658],
   [46.071523, 11.1362552],
   [46.0716212, 11.1362493],
   [46.0716892, 11.13633],
   [46.0717016, 11.1364402],
   [46.0716956, 11.1365394]],
  'count_complessivo': 5},
 23058904: {'coords': [[46.0700669, 11.1195315], [46.0700876, 11.1197601]],
  'count_complessivo': 1517},
 23066740: {'coords': [[46.0715046, 11.1194975],
   [46.0714577, 11.1194943],
   [46.0711225, 11.1195437],
   [46.0710104, 11.1195625]],
  'count_complessivo': 3437},
 23066741: {'coords': [[46.0706473, 11.1196289], [46.0705531, 11.1195479]],
  'count_complessivo': 821},
 23066966: {'coords': [[46.0677511, 11.121466],
   [46.0681452, 11.1213806],
   [46.0682642, 11.1213548],
   [46.0684385, 11.1213115],
   [46.0685261, 11.1212897],
   [46.0686443, 11.1212678]],
  'count_complessivo': 2078},
 23069364: {'coords': [[46.0697611, 11.1159155],
   [46.0697526, 11.1159495],
   [46.06975, 11.1159777],
   [46.069751, 11.116006],
   [46.0697555, 11.1160335],
   [46.0697634, 11.1160592],
   [46.0697788, 11.1160897],
   [46.0697989, 11.1161138]],
  'count_complessivo': 988},
 23234595: {'coords': [[46.0501293, 11.1308952],
   [46.0501618, 11.1308874],
   [46.0501974, 11.1308825],
   [46.0502314, 11.1308594],
   [46.0503854, 11.1307601],
   [46.0508788, 11.1304229],
   [46.0510874, 11.1302907],
   [46.0512508, 11.1301972],
   [46.0513907, 11.1301254],
   [46.0515343, 11.1300644],
   [46.051662, 11.130014],
   [46.0518697, 11.129931],
   [46.0520318, 11.1298749],
   [46.0521642, 11.1298412],
   [46.0522765, 11.1298206],
   [46.0523876, 11.1298038],
   [46.0524964, 11.129793],
   [46.0526113, 11.1297885],
   [46.0527396, 11.1297846]],
  'count_complessivo': 1056},
 23234597: {'coords': [[46.0523004, 11.1173887],
   [46.0523026, 11.1173323],
   [46.0522961, 11.1172766],
   [46.0522757, 11.1172112],
   [46.0522434, 11.1171568]],
  'count_complessivo': 214},
 23403993: {'coords': [[46.0323116, 11.1324833],
   [46.0322969, 11.1325089],
   [46.0321721, 11.1326289],
   [46.0318739, 11.132764],
   [46.031515, 11.1327982],
   [46.0312537, 11.1328077],
   [46.0311787, 11.1328096],
   [46.0308813, 11.1328205],
   [46.0304823, 11.1328341]],
  'count_complessivo': 3},
 23680878: {'coords': [[46.0700827, 11.1280032],
   [46.0702502, 11.128022],
   [46.0703787, 11.1280233],
   [46.070492, 11.1280102],
   [46.0706052, 11.1279827],
   [46.0712915, 11.1277908],
   [46.071517, 11.127743],
   [46.0715886, 11.1277871],
   [46.071613, 11.1278268],
   [46.0716324, 11.1278956],
   [46.071641, 11.1279404],
   [46.0716415, 11.1279987],
   [46.0716349, 11.128047],
   [46.0716201, 11.1280942],
   [46.0715872, 11.1281519],
   [46.0715586, 11.1281942],
   [46.0715365, 11.1282489],
   [46.0715284, 11.1283006],
   [46.0715268, 11.1283565],
   [46.0715367, 11.1284263],
   [46.0715567, 11.1284892],
   [46.0715899, 11.1285292],
   [46.0716305, 11.1285518],
   [46.071663, 11.1285586],
   [46.0716954, 11.12856],
   [46.071733, 11.1285479],
   [46.0718066, 11.1284987],
   [46.0718513, 11.1284736],
   [46.072189, 11.1282519],
   [46.0722366, 11.1282249],
   [46.0722633, 11.1282079],
   [46.0722836, 11.1281963],
   [46.072474, 11.1281028],
   [46.072555, 11.128062],
   [46.0725758, 11.12806],
   [46.0727627, 11.1280423],
   [46.0731497, 11.1280235],
   [46.0732042, 11.1280437],
   [46.0732634, 11.1280957],
   [46.0732918, 11.1281359]],
  'count_complessivo': 209},
 23733914: {'coords': [[46.0692759, 11.1287364],
   [46.0696123, 11.1285533],
   [46.0696505, 11.1285222]],
  'count_complessivo': 157},
 23734003: {'coords': [[46.0699317, 11.1280657], [46.0699423, 11.1279639]],
  'count_complessivo': 380},
 23751867: {'coords': [[46.066779, 11.1222948],
   [46.066883, 11.1230497],
   [46.0669188, 11.1233181]],
  'count_complessivo': 1427},
 23751933: {'coords': [[46.0673609, 11.1241032],
   [46.0671042, 11.1241841],
   [46.0670336, 11.1242105]],
  'count_complessivo': 2015},
 23752172: {'coords': [[46.0681489, 11.122547],
   [46.0682031, 11.1229202],
   [46.0682323, 11.1232256],
   [46.0682565, 11.1234891]],
  'count_complessivo': 2448},
 23762032: {'coords': [[46.0670336, 11.1242105],
   [46.0670609, 11.1244589],
   [46.0671305, 11.1249314],
   [46.067154, 11.1251198],
   [46.0671546, 11.1251368],
   [46.0671801, 11.1253736]],
  'count_complessivo': 1405},
 23762228: {'coords': [[46.0672986, 11.1231917],
   [46.0672834, 11.1228166],
   [46.0672696, 11.1221685]],
  'count_complessivo': 950},
 23762376: {'coords': [[46.0679214, 11.1224272],
   [46.0678345, 11.1222729],
   [46.0677412, 11.122107]],
  'count_complessivo': 2878},
 23762459: {'coords': [[46.0676623, 11.1214867],
   [46.0677381, 11.121469],
   [46.0677511, 11.121466]],
  'count_complessivo': 2054},
 23762742: {'coords': [[46.0683737, 11.1252392], [46.0683518, 11.1247826]],
  'count_complessivo': 2821},
 23762833: {'coords': [[46.0678665, 11.1257547],
   [46.0682312, 11.1253579],
   [46.0683737, 11.1252392]],
  'count_complessivo': 2136},
 23763043: {'coords': [[46.0653629, 11.1231062],
   [46.0653338, 11.1231185],
   [46.0652427, 11.123157],
   [46.0651661, 11.1231671],
   [46.0650668, 11.123137]],
  'count_complessivo': 6400},
 23763110: {'coords': [[46.0663397, 11.1260052],
   [46.066183, 11.1259188],
   [46.0659566, 11.1257932],
   [46.0657558, 11.1256832],
   [46.0655591, 11.1255747]],
  'count_complessivo': 1639},
 23763170: {'coords': [[46.0648809, 11.1280847],
   [46.0650092, 11.1281598],
   [46.0656651, 11.1285336]],
  'count_complessivo': 1431},
 23763178: {'coords': [[46.0656651, 11.1285336],
   [46.0659942, 11.1273145],
   [46.0660216, 11.1272155]],
  'count_complessivo': 852},
 23763189: {'coords': [[46.0660216, 11.1272155],
   [46.0661038, 11.127259],
   [46.0667619, 11.1276073],
   [46.0671617, 11.127815],
   [46.0672324, 11.1278544],
   [46.0672708, 11.127874]],
  'count_complessivo': 834},
 23763209: {'coords': [[46.067741, 11.128426],
   [46.0675709, 11.1282852],
   [46.0674041, 11.1281471],
   [46.0673689, 11.1281179],
   [46.0672886, 11.1280514],
   [46.0672456, 11.1280337]],
  'count_complessivo': 173},
 23763416: {'coords': [[46.0666524, 11.1190333],
   [46.0666639, 11.1191419],
   [46.0667748, 11.1201923]],
  'count_complessivo': 4859},
 23763851: {'coords': [[46.0673609, 11.1241032],
   [46.0673555, 11.1240327],
   [46.0673181, 11.1236253]],
  'count_complessivo': 809},
 23763869: {'coords': [[46.0690627, 11.1233576],
   [46.0688361, 11.1233813],
   [46.0687294, 11.1233985],
   [46.0685395, 11.1234315],
   [46.0682783, 11.1234658],
   [46.0682565, 11.1234891]],
  'count_complessivo': 1589},
 23763916: {'coords': [[46.0695223, 11.1198626],
   [46.0694859, 11.1198744],
   [46.069301, 11.119934],
   [46.0692869, 11.1199385],
   [46.0691309, 11.1199889],
   [46.0688366, 11.1200195]],
  'count_complessivo': 2115},
 23763968: {'coords': [[46.0686861, 11.1191487],
   [46.0686582, 11.1187466],
   [46.0686522, 11.1186774]],
  'count_complessivo': 2038},
 23763977: {'coords': [[46.068464, 11.1201043],
   [46.0683737, 11.1202017],
   [46.0681188, 11.1205421],
   [46.0680409, 11.1206138],
   [46.0679973, 11.1206539],
   [46.0678601, 11.1207795],
   [46.0677434, 11.1208522],
   [46.0676905, 11.120901],
   [46.0676632, 11.1209262]],
  'count_complessivo': 2654},
 23763993: {'coords': [[46.0663806, 11.1234542],
   [46.0663678, 11.123358],
   [46.06629, 11.1227714],
   [46.06624, 11.1226907]],
  'count_complessivo': 1502},
 23764020: {'coords': [[46.0665144, 11.1224055],
   [46.0664798, 11.1221149],
   [46.066554, 11.1220838],
   [46.0665465, 11.1220404]],
  'count_complessivo': 5600},
 23794856: {'coords': [[46.0698128, 11.1182454],
   [46.0697527, 11.1182632],
   [46.0696071, 11.118364]],
  'count_complessivo': 1197},
 23795382: {'coords': [[46.0699211, 11.1273286],
   [46.069982, 11.1273093],
   [46.0700646, 11.1272344],
   [46.0702467, 11.1270612],
   [46.0705348, 11.1267956]],
  'count_complessivo': 1706},
 23795535: {'coords': [[46.0692759, 11.1287364],
   [46.0689565, 11.1288966],
   [46.0686535, 11.1290659],
   [46.0681974, 11.1293038],
   [46.0679193, 11.1294608],
   [46.0677627, 11.1296102],
   [46.0676905, 11.1296887],
   [46.0676316, 11.1297529],
   [46.0671709, 11.1304027],
   [46.0670532, 11.1305795],
   [46.0669198, 11.1308942],
   [46.0667221, 11.1313606],
   [46.0666056, 11.1316453],
   [46.0665417, 11.1318344]],
  'count_complessivo': 159},
 23795538: {'coords': [[46.0700579, 11.1178874],
   [46.0700777, 11.1177285],
   [46.0702228, 11.1172576]],
  'count_complessivo': 2196},
 23795565: {'coords': [[46.0702228, 11.1172576],
   [46.0702492, 11.1171648],
   [46.0702624, 11.1170913],
   [46.0702591, 11.1169646],
   [46.0702158, 11.116821],
   [46.070173, 11.1167347],
   [46.0700414, 11.1165273]],
  'count_complessivo': 2204},
 23795568: {'coords': [[46.0662275, 11.114379],
   [46.0660795, 11.1142932],
   [46.0660037, 11.1142493],
   [46.0655485, 11.1140117],
   [46.0652763, 11.1138686],
   [46.0651512, 11.1138029],
   [46.0650894, 11.1137705],
   [46.0648267, 11.113651],
   [46.064706, 11.1135921],
   [46.0645179, 11.1135136],
   [46.0643351, 11.1134453],
   [46.0641639, 11.1133819],
   [46.0639514, 11.1133045],
   [46.0637002, 11.1132247],
   [46.0634797, 11.1131527],
   [46.0633193, 11.113106],
   [46.0631222, 11.1130525],
   [46.0628109, 11.1129723],
   [46.0625987, 11.1129292]],
  'count_complessivo': 2357},
 23795654: {'coords': [[46.0653629, 11.1231062],
   [46.0653725, 11.1239505],
   [46.0654198, 11.1244608],
   [46.0654836, 11.1247514],
   [46.0654889, 11.1247801],
   [46.0654911, 11.1248055],
   [46.0654863, 11.1248303],
   [46.065479, 11.124849],
   [46.0654664, 11.1248635]],
  'count_complessivo': 912},
 23795655: {'coords': [[46.0657149, 11.1211459],
   [46.0657118, 11.1211893],
   [46.0653629, 11.1231062]],
  'count_complessivo': 4066},
 23795664: {'coords': [[46.0645977, 11.1214687],
   [46.0647043, 11.121461],
   [46.0647492, 11.1213838],
   [46.0647686, 11.1213466],
   [46.0648746, 11.1211594],
   [46.0648937, 11.121137],
   [46.0649225, 11.1211275],
   [46.0654197, 11.1211443]],
  'count_complessivo': 539},
 23795665: {'coords': [[46.0663852, 11.1210496],
   [46.0665071, 11.1210276],
   [46.0665614, 11.121022],
   [46.0666115, 11.1210169],
   [46.0666602, 11.1210169]],
  'count_complessivo': 3660},
 23795676: {'coords': [[46.0668711, 11.1210492],
   [46.0667705, 11.1210629],
   [46.0667144, 11.1210409]],
  'count_complessivo': 2325},
 23795681: {'coords': [[46.0663852, 11.1210496],
   [46.0661586, 11.1211285],
   [46.0661065, 11.1211467]],
  'count_complessivo': 3702},
 23800071: {'coords': [[46.0734977, 11.1208969],
   [46.0734944, 11.1208355],
   [46.0734764, 11.1207601],
   [46.073443, 11.1207144],
   [46.0733941, 11.1206726],
   [46.0727937, 11.1202688]],
  'count_complessivo': 1681},
 23807827: {'coords': [[46.0418481, 11.1313902],
   [46.0416643, 11.1313444],
   [46.0415789, 11.1313386],
   [46.0414899, 11.1313518],
   [46.0412812, 11.1314331],
   [46.0409056, 11.1316138],
   [46.040693, 11.1317165],
   [46.0405802, 11.1317688],
   [46.0404326, 11.1318356],
   [46.0402971, 11.1318927],
   [46.0396469, 11.1321869],
   [46.0393623, 11.1323157],
   [46.0392102, 11.1323815]],
  'count_complessivo': 39},
 23807936: {'coords': [[46.0419591, 11.1310455],
   [46.0419947, 11.1310868],
   [46.0420362, 11.1311145],
   [46.042081, 11.1311268],
   [46.0421313, 11.1311218]],
  'count_complessivo': 128},
 23808052: {'coords': [[46.047022, 11.1269065],
   [46.0469672, 11.1268054],
   [46.0469424, 11.126739],
   [46.0469375, 11.12665],
   [46.0469374, 11.1258027],
   [46.0469129, 11.1256341]],
  'count_complessivo': 84},
 23808336: {'coords': [[46.0493392, 11.1223561],
   [46.0493082, 11.1223576],
   [46.0492782, 11.1223741],
   [46.048702, 11.1232079],
   [46.0479051, 11.1243118],
   [46.0477422, 11.1245202],
   [46.0474114, 11.1249432],
   [46.0470099, 11.1254996],
   [46.0469129, 11.1256341]],
  'count_complessivo': 130},
 23814986: {'coords': [[46.0664974, 11.117434],
   [46.0664923, 11.1173351],
   [46.0664638, 11.1170396],
   [46.0664646, 11.1169837],
   [46.0664652, 11.1169231],
   [46.0663665, 11.1158668]],
  'count_complessivo': 3694},
 23814996: {'coords': [[46.0664974, 11.117434],
   [46.0665935, 11.1174146],
   [46.0667266, 11.1173877],
   [46.0667597, 11.117381],
   [46.0670857, 11.1173151],
   [46.0673008, 11.1172739],
   [46.0680121, 11.1171283],
   [46.0681191, 11.1171294]],
  'count_complessivo': 995},
 23815011: {'coords': [[46.0681191, 11.1171294],
   [46.0681601, 11.1171031],
   [46.0686021, 11.1169041],
   [46.068813, 11.1168193],
   [46.0688625, 11.1168212],
   [46.068942, 11.1168633],
   [46.0690898, 11.116953],
   [46.0694474, 11.1171906],
   [46.0696085, 11.1174443],
   [46.0697925, 11.1176638]],
  'count_complessivo': 309},
 23854157: {'coords': [[46.0761515, 11.1118285],
   [46.0761056, 11.1117878],
   [46.0760761, 11.1117682],
   [46.0760466, 11.1117539],
   [46.0759882, 11.1117347],
   [46.0759241, 11.1117236],
   [46.0758273, 11.1117283],
   [46.0755227, 11.1117432],
   [46.0754897, 11.1117407],
   [46.0754443, 11.1117372],
   [46.0753881, 11.1117209],
   [46.0753399, 11.111707],
   [46.0752556, 11.1116561],
   [46.0752367, 11.1116447],
   [46.0750384, 11.1115306]],
  'count_complessivo': 18},
 23854200: {'coords': [[46.0769565, 11.1138904],
   [46.0769474, 11.1137986],
   [46.0769368, 11.1136818],
   [46.0769363, 11.1136226],
   [46.0769395, 11.1135634],
   [46.0769523, 11.113447],
   [46.0769665, 11.113389],
   [46.0769834, 11.1133465],
   [46.077021, 11.113256],
   [46.0771479, 11.1130333]],
  'count_complessivo': 2},
 23854201: {'coords': [[46.0772269, 11.1147407],
   [46.07751, 11.1156413],
   [46.0775296, 11.1157096]],
  'count_complessivo': 274},
 23854473: {'coords': [[46.0762891, 11.1218353], [46.076377, 11.1214077]],
  'count_complessivo': 1285},
 23854590: {'coords': [[46.0760234, 11.1228263],
   [46.0759178, 11.1228113],
   [46.0758312, 11.122815],
   [46.0757768, 11.1228282],
   [46.0756936, 11.1228739]],
  'count_complessivo': 555},
 23854591: {'coords': [[46.0770797, 11.1235097],
   [46.07683, 11.1233452],
   [46.0764993, 11.1231172],
   [46.0764477, 11.1230863]],
  'count_complessivo': 1622},
 23854594: {'coords': [[46.0764477, 11.1230863],
   [46.0761443, 11.1229071],
   [46.0760234, 11.1228263]],
  'count_complessivo': 1594},
 23854595: {'coords': [[46.0853162, 11.118715],
   [46.085276, 11.1188321],
   [46.0852225, 11.1189304],
   [46.0851547, 11.1190309],
   [46.0850578, 11.119098],
   [46.085019, 11.1191204],
   [46.0849471, 11.1191621],
   [46.0845079, 11.119416],
   [46.0843448, 11.1195103],
   [46.0843255, 11.1195215],
   [46.0840851, 11.1196605],
   [46.0840126, 11.1197033],
   [46.0839319, 11.1197511],
   [46.0836022, 11.1200574]],
  'count_complessivo': 585},
 23854781: {'coords': [[46.0771965, 11.1146406],
   [46.077168, 11.1146548],
   [46.0771608, 11.1146591],
   [46.0768991, 11.114826],
   [46.0767204, 11.1149096],
   [46.0766708, 11.1149346],
   [46.0761603, 11.1151518],
   [46.0756638, 11.1153158],
   [46.0749912, 11.1155073],
   [46.074871, 11.1155332],
   [46.0744838, 11.1155878],
   [46.0741032, 11.1156077],
   [46.0740619, 11.1156104],
   [46.0738186, 11.1156152],
   [46.0736177, 11.1156053],
   [46.0735446, 11.1156035],
   [46.0733482, 11.1155879],
   [46.0731088, 11.115557],
   [46.072794, 11.1155049],
   [46.072518, 11.115443],
   [46.0722413, 11.1153662],
   [46.0718098, 11.1152261],
   [46.0716777, 11.11518],
   [46.0715565, 11.1151446]],
  'count_complessivo': 986},
 23857969: {'coords': [[46.0722321, 11.1247993],
   [46.073054, 11.1249622],
   [46.0731013, 11.1249697],
   [46.0737523, 11.124937],
   [46.0737968, 11.1249363],
   [46.0740074, 11.1249343],
   [46.0742607, 11.1249349]],
  'count_complessivo': 1183},
 23857970: {'coords': [[46.0762101, 11.1249523],
   [46.076187, 11.1248707],
   [46.0760584, 11.1244168],
   [46.0760282, 11.12431]],
  'count_complessivo': 151},
 23858004: {'coords': [[46.0760282, 11.12431],
   [46.0764929, 11.1240444],
   [46.0766621, 11.1239477],
   [46.0769409, 11.1237883]],
  'count_complessivo': 1604},
 23884317: {'coords': [[46.075615, 11.1067014], [46.0755786, 11.1060587]],
  'count_complessivo': 1},
 23884318: {'coords': [[46.0755786, 11.1060587],
   [46.0755801, 11.1059701],
   [46.0755825, 11.1058923],
   [46.0755951, 11.1058352],
   [46.0756096, 11.1057795],
   [46.0756353, 11.1057107],
   [46.0756693, 11.1056513],
   [46.0757681, 11.1055552],
   [46.0758826, 11.105464],
   [46.0759822, 11.1053713],
   [46.076052, 11.1052866],
   [46.0761941, 11.1050772],
   [46.076311, 11.1048595],
   [46.0763552, 11.104777],
   [46.0767662, 11.1040288],
   [46.0768643, 11.1038718],
   [46.076994, 11.1037274],
   [46.0771019, 11.1036381],
   [46.0772464, 11.1035556],
   [46.0773727, 11.1035147],
   [46.077544, 11.1034939],
   [46.0775929, 11.1035],
   [46.0776524, 11.1035111]],
  'count_complessivo': 1},
 23884550: {'coords': [[46.067973, 11.1164369], [46.0679574, 11.1163518]],
  'count_complessivo': 38},
 23884551: {'coords': [[46.0457036, 11.11373],
   [46.0456608, 11.1137786],
   [46.0456157, 11.1138277]],
  'count_complessivo': 1},
 23888166: {'coords': [[46.0475491, 11.1273332],
   [46.0476526, 11.1272274],
   [46.0478193, 11.1270577],
   [46.0479686, 11.1268948],
   [46.0485078, 11.1263086],
   [46.0485489, 11.1262626],
   [46.0487397, 11.1260384],
   [46.0488555, 11.1259023],
   [46.0490314, 11.1256957],
   [46.0492205, 11.125479],
   [46.0493037, 11.1253699],
   [46.0494967, 11.1251205],
   [46.0495656, 11.1250206],
   [46.0498837, 11.1246006],
   [46.0498968, 11.1245823],
   [46.0499846, 11.12446],
   [46.0500701, 11.1243452],
   [46.0502671, 11.1240696],
   [46.050443, 11.1238436],
   [46.0504897, 11.1237779]],
  'count_complessivo': 312},
 23888167: {'coords': [[46.0477323, 11.1260191],
   [46.0472376, 11.1266233],
   [46.047022, 11.1269065]],
  'count_complessivo': 49},
 23888168: {'coords': [[46.0469129, 11.1256341], [46.0468022, 11.1254018]],
  'count_complessivo': 36},
 23888170: {'coords': [[46.046705, 11.1252067],
   [46.0466025, 11.1249906],
   [46.0465589, 11.1249408],
   [46.046482, 11.1248932],
   [46.0463513, 11.1248748],
   [46.0462083, 11.1249177],
   [46.0459938, 11.1250918],
   [46.0457735, 11.1252464],
   [46.0455479, 11.1254048],
   [46.0454347, 11.1254105],
   [46.0453715, 11.1254044],
   [46.0452861, 11.1253489],
   [46.0452425, 11.1252874],
   [46.0452129, 11.1251988],
   [46.0451891, 11.1250901],

In [36]:
with open('ways_id.json', 'w') as f:
    json.dump(d, f)

### Map selecting month

In [14]:
df = pd.read_parquet('../produced_datasets/map_matched_edges_ids.parquet')
df = df.reset_index()
f = open('../produced_datasets/ways_id.json')
d = json.load(f)

In [15]:
def compute_route_freq(df, month, year): 
    '''
    helper function to compute the routes and their frequency for the selected month
    '''
    data_selected_month = df.loc[(df.month == month) & (df.year == year)]
    data_selected_month = data_selected_month.reset_index()
    
    list_ways = []
    for row in range(len(data_selected_month)):
        list_ways.extend(data_selected_month.edge_ids[row])
    count_freq = Counter(list_ways) # count how many times passed through
    list_ways = list(set(list_ways))
    
    routes = []
    cnt = []
    for road in list_ways:
        route = d[road]['coords'] # coordinates (from way_id.json)
        routes.append(route)
        cnt.append(count_freq[road]) # num. times passed through (for the given month -> from counter above)
        
    return routes, cnt


def render_map(data=df, month=2, year=2021):
    '''
    render the map 
    '''
    routes, cnt = compute_route_freq(data, month, year) # helper function
    
    f_map = folium.Map(location=[46.066,11.133], tiles='cartodbdark_matter', zoom_start=14) #  tiles="cartodbdark_matter" "Stamen Toner" "OpenStreetMap"

    colormap = cm.LinearColormap(colors=['cyan', 'yellow', 'orange', 'red'], # ['darkblue', 'blue', 'cyan', 'yellow', 'orange', 'red']
                                index = np.linspace(min(cnt), max(cnt), num=4),
                                vmin = min(cnt), vmax = max(cnt), 
                                caption='Number of times the segment was passed through')
        
    fg = folium.FeatureGroup(name='overpass_tratte_forti')    


    for way in range(len(routes)): 
        color = colormap(cnt[way])
        w = min(cnt[way]/100 , 5)
        folium.vector_layers.PolyLine(routes[way], color=color, weight=w).add_to(fg)


    f_map.add_child(fg)
    f_map.add_child(colormap)

    return f_map

In [18]:
import panel as pn
import param

# compute routes and their frequency for the selected month
def compute_route_freq(month, year): 
    '''
    helper function to compute the routes and their frequency for the selected month
    '''
    data_selected_month = df.loc[(df.month == month) & (df.year == year)]
    data_selected_month = data_selected_month.reset_index()
    
    list_ways = []
    for row in range(len(data_selected_month)):
        list_ways.extend(data_selected_month.edge_ids[row])
    count_freq = Counter(list_ways) # count how many times passed through
    list_ways = list(set(list_ways))
    
    routes = []
    cnt = []
    for road in list_ways:
        route = d[str(road)]['coords'] # coordinates (from way_id.json)
        routes.append(route)
        cnt.append(count_freq[road]) # num. times passed through (for the given month -> from counter above)
        
    return routes, cnt


# base map
def get_map():
    return folium.Map(location=[46.066667,11.133333], tiles='Stamen Toner', zoom_start=14) 

map = get_map()
# pn.panel(map, height=400)


# plot data on map
def plot_data(map, df, month, year):
    '''
    render the map 
    '''
    routes, cnt = compute_route_freq(month, year)# helper function
    
    colormap = cm.LinearColormap(colors=['yellow', 'orange', 'red', 'darkred'], 
                                index = np.linspace(min(cnt), max(cnt), num=4),
                                vmin = min(cnt), vmax = max(cnt), 
                                caption='Number of times the segment was passed through')
    
    fg = folium.FeatureGroup(name='overpass_tratte_forti')    

    for way in range(len(routes)): 
        color = colormap(cnt[way])
        w = min(cnt[way]/10, 5)
        folium.vector_layers.PolyLine(routes[way], color=color, weight=w).add_to(fg)

    map.add_child(fg)
    map.add_child(colormap)

    return map

In [28]:
# Parameterized -> add slider
class PanelFoliumMap(param.Parameterized):
    month = param.Integer(2, bounds=(1,12))
    year = param.Integer(2021, bounds=(2020,2022))
        
    def __init__(self, **params):
        super().__init__(**params)
        self.map = get_map()
        self.folium_pane = pn.pane.plot.Folium(sizing_mode="stretch_both", min_height=500, min_width=900, margin=0)    
        self.view = pn.Column(pn.Row(self.param.month, self.param.year), 
                              self.folium_pane) 
        self._update_map()

    @param.depends("month", "year", watch=True)
    def _update_map(self):
        self.map = get_map()
        df_month = compute_route_freq(month=self.month, year=self.year)
        plot_data(self.map, df_month, self.month, year=self.year)
        self.folium_pane.object = self.map

        
app = PanelFoliumMap()
app.view

Column
    [0] Row
        [0] IntSlider(end=12, name='Month', start=1, value=2)
        [1] IntSlider(end=2022, name='Year', start=2020, value=2021)
    [1] Folium(Map, margin=0, min_height=500, min_width=900, sizing_mode='stretch_both')

In [53]:
# app.view.save('panel.html')
pn.template.FastListTemplate(site="Panel", title="Folium", main=["Most Travelled Routes", PanelFoliumMap().view]).servable();
# as administrator:
# netstat -ano | findstr < Port Number aka 5006 >
# taskkill /F /PID < Process Id >
# anaconda:
# panel serve interactive_tratte_forti.ipynb

### Map selecting time of the day

In [44]:
df = pd.read_parquet('../produced_datasets/map_matched_edges_ids.parquet')
df = df.reset_index()
df.head()

,index,unique_id,route,matched,dates,month,year,edge_ids
0,0,00000bf0-0000-1000-a6a0-5b7d6a617b60_2020-11-30,"[[46.069691, 11.121241], [46.069716, 11.121509...",True,2020-11-30,11,2020,"[748981520, 748981521, 48769827, 72847149, 177..."
1,1,00001d90-0000-1000-8b30-5b7d6a617b60_2020-11-30,"[[46.07016, 11.120398], [46.070181, 11.12065],...",True,2020-11-30,11,2020,"[748981521, 24771360, 48769827, 72847149, 1771..."
2,2,0000210d-0000-1000-8d7d-5b7d6a617b60_2020-11-30,"[[46.067214, 11.126787], [46.067211, 11.126772...",True,2020-11-30,11,2020,"[308335488, 295396001, 574541250, 109372547, 1..."
3,4,00000e00-0000-1000-9ab0-5b7d6a617b60_2020-11-30,"[[46.069695, 11.121283], [46.069716, 11.121509...",True,2020-11-30,11,2020,"[227756256, 227756257, 24771362, 216745509, 24..."
4,7,00002538-0000-1000-8f68-5b7d6a617b60_2020-11-30,"[[46.067217, 11.126806], [46.067221, 11.126829]]",True,2020-11-30,11,2020,[153939403]

In [45]:
# get timestamps 
orig_df= pd.read_parquet('../data/trips_pointv3_cleaned.parquet')

In [46]:
new_df = orig_df.groupby('unique_id', as_index=False).aggregate({"point_timestamp":lambda x: x.to_list()})

In [47]:
start_time = {}
for i in range(len(new_df)):
    start_time[new_df.at[i, 'unique_id']] = min(new_df.at[i, 'point_timestamp'])

In [48]:
# add timestamp to map-matched dataframe
tmstmp = []
for row in range(len(df)):
    tmstmp.append(start_time[df.at[row, 'unique_id']])

In [49]:
df['start_time'] = tmstmp
df = df.drop(['index'], axis=1)
df.head(3)

,unique_id,route,matched,dates,month,year,edge_ids,start_time
0,00000bf0-0000-1000-a6a0-5b7d6a617b60_2020-11-30,"[[46.069691, 11.121241], [46.069716, 11.121509...",True,2020-11-30,11,2020,"[748981520, 748981521, 48769827, 72847149, 177...",2020-11-30 14:32:20+00:00
1,00001d90-0000-1000-8b30-5b7d6a617b60_2020-11-30,"[[46.07016, 11.120398], [46.070181, 11.12065],...",True,2020-11-30,11,2020,"[748981521, 24771360, 48769827, 72847149, 1771...",2020-11-30 15:37:44+00:00
2,0000210d-0000-1000-8d7d-5b7d6a617b60_2020-11-30,"[[46.067214, 11.126787], [46.067211, 11.126772...",True,2020-11-30,11,2020,"[308335488, 295396001, 574541250, 109372547, 1...",2020-11-30 15:42:50+00:00

In [50]:
f = open('../produced_datasets/ways_id.json')
d = json.load(f) # way_id : { coords: [list of lists], count_complessivo: int }

In [51]:
def compute_route_freq(start_h, end_h): 
    '''
    helper function to compute the routes and their frequency for the timewindow
    '''
    data_selected = df.loc[(df.start_time.dt.hour >= start_h) & (df.start_time.dt.hour < end_h)]
    data_selected = data_selected.reset_index()
    
    list_ways = []
    for row in range(len(data_selected)):
        list_ways.extend(data_selected.edge_ids[row])
    count_freq = Counter(list_ways) # count how many times passed through
    list_ways = list(set(list_ways))
    
    routes = []
    cnt = []
    for road in list_ways:
        route = d[str(road)]['coords'] # coordinates (from way_id.json)
        routes.append(route)
        cnt.append(count_freq[road]) # num. times passed through (for the given month -> from counter above)
        
    return routes, cnt


def get_map():
    return folium.Map(location=[46.066667,11.133333], tiles='Stamen Toner', zoom_start=14) 

map = get_map()

def render_map(map, df, month, year):
    '''
    render the map 
    '''
    routes, cnt = compute_route_freq(month, year)# helper function
    
    colormap = cm.LinearColormap(colors=['yellow', 'orange', 'red', 'darkred'], 
                                index = np.linspace(min(cnt), max(cnt), num=4),
                                vmin = min(cnt), vmax = max(cnt), 
                                caption='Number of times the segment was passed through')
    
    fg = folium.FeatureGroup(name='overpass_tratte_forti')    

    for way in range(len(routes)): 
        color = colormap(cnt[way])
        w = min(cnt[way]/10, 5)
        folium.vector_layers.PolyLine(routes[way], color=color, weight=w).add_to(fg)

    map.add_child(fg)
    map.add_child(colormap)

    return map

In [ ]:
# Parameterized -> add slider
pn.extension()

class PanelFoliumMap(param.Parameterized):
    start_hour = param.Integer(14, bounds=(0,23))
    end_hour = param.Integer(15, bounds=(0,23))
        
    def __init__(self, **params):
        super().__init__(**params)
        self.map = get_map()
        self.folium_pane = pn.pane.plot.Folium(sizing_mode="stretch_both", min_height=500, min_width=900, margin=0)     
        self.view = pn.Column(pn.Row(self.param.start_hour, self.param.end_hour), 
                              self.folium_pane) 
        self._update_map()

    @param.depends("start_hour", "end_hour", watch=True)
    def _update_map(self):
        self.map = get_map()
        df_select = compute_route_freq(start_h=self.start_hour, end_h=self.end_hour)
        render_map(self.map, df_select, self.start_hour, self.end_hour)
        self.folium_pane.object = self.map

        
app = PanelFoliumMap()
app.view