## Content: visualize the most travelled roads
Use map-matched data to create a network showing the most travelled paths.

In [1]:
import pandas as pd
import geopandas as gpd
import json
import requests
from shapely.geometry.linestring import LineString, Point
import overpy
import folium
import folium.plugins
import branca
import branca.colormap as cm
import statistics
from collections import Counter
import numpy as np
import requests
import xml.etree.ElementTree as ET
import warnings
warnings.filterwarnings("ignore")

### Naive Approach

In [2]:
df = pd.read_parquet("../data/map_matched_routes.parquet")
df = df[df.matched == True] # only matched routes
df = df.reset_index()

In [3]:
d=[]
for i in range(len(df)):
    d.append(df.unique_id[i][-10:].split('-')[0]+df.unique_id[i][-10:].split('-')[1]+df.unique_id[i][-10:].split('-')[2])
df['dates'] = d
df['dates'] = pd.to_datetime(df['dates'], format='%Y%m%d')

In [4]:
# select month
df['month'] = df['dates'].dt.month
df['year'] = df['dates'].dt.year
df = df[df.month == 5]
df = df[df.year == 2021]
df = df.reset_index()
df = df.drop(['level_0', 'index'], axis=1)
df

,unique_id,route,matched,dates,month,year
0,7b3822b21ad6_2021-05-01,"[[46.094015, 11.118042], [46.094006, 11.118092...",True,2021-05-01,5,2021
1,0000249f-0000-1000-a49f-5b7d6a617b60_2021-05-01,"[[46.071505, 11.124385], [46.071556, 11.12444]...",True,2021-05-01,5,2021
2,00000255-0000-1000-80b5-5b7d6a617b60_2021-05-01,"[[46.06264, 11.130528], [46.062607, 11.130478]...",True,2021-05-01,5,2021
3,00000311-0000-1000-8131-5b7d6a617b60_2021-05-01,"[[46.066735, 11.119816], [46.066664, 11.119142...",True,2021-05-01,5,2021
4,000005a3-0000-1000-82e3-5b7d6a617b60_2021-05-01,"[[46.067347, 11.127076], [46.067383, 11.126828...",True,2021-05-01,5,2021
...,...,...,...,...,...,...
5973,00001f4a-0000-1000-8aaa-5b7d6a617b60_2021-05-31,"[[46.063282, 11.123642], [46.063275, 11.123555...",True,2021-05-31,5,2021
5974,929c30292fc2_2021-05-31,"[[46.071694, 11.121318], [46.072025, 11.121522...",True,2021-05-31,5,2021
5975,2c5de7606219_2021-05-31,"[[46.068837, 11.119139], [46.068787, 11.119144...",True,2021-05-31,5,2021
5976,29d85ecda468_2021-05-31,"[[46.059655, 11.125811], [46.05906, 11.124982]...",True,2021-05-31,5,2021
5977,acb2eb1cb342_2021-05-31,"[[46.059037, 11.124956], [46.059037, 11.124956...",True,2021-05-31,5,2021

In [17]:
s=[]
for i in range(len(df)):
    for lsr in range(len(df.route[i])-1):
        segment = ((df.route[i][lsr][1], df.route[i][lsr][0]), (df.route[i][lsr+1][1], df.route[i][lsr+1][0])) # lon-lat
        #segment = LineString(segment)
        s.append(segment)

In [18]:
from collections import Counter
occurrences = Counter(s)
len(occurrences)

23282

In [19]:
max(occurrences.values()), min(occurrences.values()), statistics.mean(occurrences.values()), statistics.median(occurrences.values())

(474, 1, 13.7469289579933, 2.0)

In [20]:
f_map = folium.Map(location=[46.066,11.133], tiles="OpenStreetMap", zoom_start=12)


colormap = cm.LinearColormap(colors=['darkblue', 'blue', 'cyan', 'yellow', 'orange', 'red'],
                            index = np.linspace(min(occurrences.values()), max(occurrences.values()), num=6),
                            vmin = min(occurrences.values()), vmax = max(occurrences.values()), 
                            caption='Number of times the segment was passed by')


fg = folium.FeatureGroup(name='naive')    

for lstr in occurrences.keys(): 
    # fg = folium.FeatureGroup(name=str(df.month[i])) # a feature group for each month
    color = colormap(occurrences[lstr])
    w = occurrences[lstr]/50
    lstr = [[lstr[0][1], lstr[0][0]], [lstr[1][1], lstr[1][0]]]
    folium.vector_layers.PolyLine(lstr, color=color, weight=w).add_to(fg)


f_map.add_child(fg)
f_map.add_child(colormap)

f_map.save('naive_map_tratte_forti.html')

### Better solution
1. Use map-matched data and map-match the route again with Valhalla docker using `trace_attributes` mode and the using as `shape_match` the `edge_walk` algorithm. According to the [documentation](https://valhalla.readthedocs.io/en/latest/api/map-matching/api-reference/#shape-matching-parameters), this algorithm should only be used when the input route is already map-matched or at least is precise enough to be really closed to the OSM ways.

2. From the response, extract the way ids. Each route will be assigned to a list of ways ids, corresponding to the segment of the street network that route crosses.

3. Get the count of how many times each segment appears, using the way ids. Finally, use these ids to query the [Overpass API](https://overpass-turbo.eu/#) to get the matching coordinates of the corresponding segments and plot it on the map according to their frequency.  The documentation and basic examples are available at this [link](https://python-overpy.readthedocs.io/en/latest/example.html#ways). To avoid running into _OverpassTooManyRequests_, the [docker image](https://github.com/wiktorn/Overpass-API) for the Overpass API was used.

In [47]:
df

,unique_id,route,matched,dates,month,year
0,7b3822b21ad6_2021-05-01,"[[46.094015, 11.118042], [46.094006, 11.118092...",True,2021-05-01,5,2021
1,0000249f-0000-1000-a49f-5b7d6a617b60_2021-05-01,"[[46.071505, 11.124385], [46.071556, 11.12444]...",True,2021-05-01,5,2021
2,00000255-0000-1000-80b5-5b7d6a617b60_2021-05-01,"[[46.06264, 11.130528], [46.062607, 11.130478]...",True,2021-05-01,5,2021
3,00000311-0000-1000-8131-5b7d6a617b60_2021-05-01,"[[46.066735, 11.119816], [46.066664, 11.119142...",True,2021-05-01,5,2021
4,000005a3-0000-1000-82e3-5b7d6a617b60_2021-05-01,"[[46.067347, 11.127076], [46.067383, 11.126828...",True,2021-05-01,5,2021
...,...,...,...,...,...,...
5973,00001f4a-0000-1000-8aaa-5b7d6a617b60_2021-05-31,"[[46.063282, 11.123642], [46.063275, 11.123555...",True,2021-05-31,5,2021
5974,929c30292fc2_2021-05-31,"[[46.071694, 11.121318], [46.072025, 11.121522...",True,2021-05-31,5,2021
5975,2c5de7606219_2021-05-31,"[[46.068837, 11.119139], [46.068787, 11.119144...",True,2021-05-31,5,2021
5976,29d85ecda468_2021-05-31,"[[46.059655, 11.125811], [46.05906, 11.124982]...",True,2021-05-31,5,2021
5977,acb2eb1cb342_2021-05-31,"[[46.059037, 11.124956], [46.059037, 11.124956...",True,2021-05-31,5,2021

In [5]:
edge_ids=[]
ids = df.unique_id.to_list()
for id in range(len(ids)):
    df_temp = df[df.unique_id==ids[id]]
    df_points = pd.DataFrame({'lon':[el[1] for i in df_temp.route for el in i], 'lat':[el[0] for i in df_temp.route for el in i]})

    # request
    meili_coordinates = df_points.to_json(orient='records')
    meili_head = '{"shape":'
    meili_tail = ""","search_radius": 300, "shape_match":"edge_walk", "costing":"bicycle", "format":"osrm"}""" # use 'shape_match' : 'edge_walk'
    meili_request_body = meili_head + meili_coordinates + meili_tail
    url = "http://localhost:8002/trace_attributes" # use /trace_attributes 
    headers = {'Content-type': 'application/json'}
    data = str(meili_request_body)

    r = requests.post(url, data=data, headers=headers)
    
    response_text = json.loads(r.text)

    if r.status_code == 200:
        l=[]
        for i in range(len(response_text['edges'])):
            l.append(response_text['edges'][i]['way_id']) #, response_text['osm_changeset'])

        edge_ids.append(list(set(l)))
    else:
        edge_ids.append([])

In [48]:
df['edge_ids'] = edge_ids

In [49]:
df = df[df['edge_ids'].map(lambda d: len(d)) > 0] # remove rows where edge_ids is empty

In [6]:
c = []
for el in edge_ids:
    c.extend(el)
c = Counter(c)
c

Counter({170076129: 11,
         307993862: 21,
         170076124: 12,
         25874135: 9,
         25874489: 25,
         170076123: 5,
         97111260: 24,
         170076127: 6,
         80410756: 10,
         23952134: 61,
         240092039: 79,
         222748808: 55,
         80410759: 9,
         97084819: 35,
         229137174: 137,
         216745509: 226,
         150886566: 32,
         770864809: 28,
         127209003: 276,
         68286129: 84,
         23857969: 82,
         223023923: 131,
         150886581: 32,
         150886597: 79,
         24581836: 59,
         150886604: 51,
         23858004: 147,
         150886613: 44,
         150886616: 37,
         150886618: 74,
         227756257: 231,
         144843361: 50,
         150886625: 43,
         150886629: 31,
         144843368: 80,
         754578288: 145,
         80410751: 10,
         24916544: 41,
         24916515: 61,
         88597865: 45,
         24449618: 33,
         24443798: 41,
         88597881: 41,
         24443801: 32,
         24443806: 24,
         689085688: 112,
         22986084: 349,
         27120102: 265,
         27120103: 270,
         80767270: 103,
         23814986: 337,
         37932920: 174,
         406632789: 174,
         406632788: 155,
         23763416: 491,
         37112955: 105,
         637268699: 134,
         829951745: 112,
         24696066: 88,
         240607362: 136,
         154140545: 237,
         240092040: 138,
         260532243: 109,
         84690453: 99,
         24789912: 108,
         308178202: 136,
         84690459: 154,
         84690461: 159,
         72232741: 54,
         72232747: 60,
         68286127: 116,
         24755378: 153,
         23795382: 179,
         23951162: 54,
         30076096: 107,
         22986312: 190,
         936412752: 116,
         35209301: 158,
         974959832: 259,
         154140543: 50,
         149811076: 652,
         223044487: 467,
         394382599: 535,
         137868938: 498,
         394382605: 526,
         748981520: 154,
         692614929: 502,
         748981521: 208,
         23762459: 179,
         75417888: 180,
         223008813: 566,
         72847149: 321,
         24094895: 388,
         24094897: 321,
         758131123: 543,
         23764020: 524,
         24094901: 652,
         452934469: 368,
         34663493: 232,
         23795655: 357,
         23795665: 333,
         27503570: 200,
         74502611: 315,
         31301717: 592,
         574541269: 695,
         23066966: 182,
         23795681: 335,
         23763043: 549,
         1055608294: 168,
         583331560: 333,
         153639916: 181,
         133370605: 213,
         42288378: 599,
         574537084: 368,
         24917615: 146,
         84690448: 147,
         97121841: 260,
         35209300: 207,
         23763968: 171,
         118389121: 589,
         712328840: 133,
         712328841: 197,
         24054411: 89,
         306203532: 98,
         306203531: 97,
         1058552718: 136,
         1058552719: 151,
         1058552717: 86,
         191633686: 97,
         191633698: 76,
         657200041: 285,
         24443820: 125,
         68286128: 286,
         68286131: 284,
         24443828: 115,
         24226869: 625,
         223001538: 64,
         37134283: 112,
         97236434: 90,
         24161642: 794,
         715573882: 146,
         78461182: 56,
         145445009: 129,
         153639955: 227,
         23951893: 88,
         24435353: 94,
         153639967: 226,
         145445025: 127,
         163225633: 128,
         29278369: 74,
         150886564: 53,
         150886565: 63,
         153639976: 224,
         150886569: 55,
         150886568: 48,
         150886573: 60,
         150886579: 58,
         163225657: 150,
         685675711: 128,
         83738049: 86,
         483221951: 50,
         150886595: 54,
         150886596: 52,
         483221953: 50,
         483221958: 46,
         163225671: 128,
         150886593: 61,
         483221965: 57,
         483221967: 57,
         150886609: 50,
         150886620: 44,
         150886626: 53,
         150886630: 58,
         99752052: 74,
         990948257: 68,
         990948261: 70,
         153639979: 200,
         108731448: 99,
         27503568: 104,
         27503569: 87,
         97111270: 40,
         755263200: 303,
         755263201: 300,
         306120648: 267,
         97236424: 275,
         97749768: 143,
         66860331: 303,
         68286123: 310,
         306120651: 290,
         306120650: 111,
         138790575: 3,
         97236432: 331,
         42288374: 103,
         24436838: 182,
         37016910: 123,
         37016912: 36,
         752730099: 259,
         42288372: 154,
         752730100: 277,
         97251479: 92,
         1057256027: 25,
         151230172: 108,
         78455812: 5,
         29227244: 37,
         75319181: 29,
         1055765966: 2,
         1055765967: 17,
         32507309: 70,
         307104563: 21,
         80375834: 12,
         25572607: 105,
         34663434: 324,
         24443788: 95,
         24054414: 244,
         24095640: 270,
         23763993: 127,
         295396001: 190,
         140303931: 404,
         23951199: 425,
         23951201: 121,
         239979891: 189,
         23751933: 184,
         24695422: 92,
         42288376: 105,
         24755681: 185,
         109372515: 49,
         574541253: 52,
         23763110: 130,
         37015405: 78,
         23762833: 177,
         260532241: 154,
         260532242: 79,
         23762742: 227,
         24094905: 65,
         574537082: 236,
         764391340: 10,
         307617082: 12,
         706503614: 28,
         82591422: 30,
         706503615: 23,
         23058125: 18,
         82078035: 20,
         170076125: 11,
         97230174: 7,
         170076128: 3,
         170076126: 7,
         161960035: 30,
         161960037: 23,
         161960041: 15,
         231754242: 51,
         694717068: 56,
         24772511: 72,
         34663338: 242,
         113824568: 61,
         113824575: 59,
         223027652: 179,
         80767309: 48,
         71520728: 55,
         71520472: 55,
         23795676: 225,
         292214785: 147,
         689006850: 149,
         775625760: 36,
         29310573: 67,
         914173107: 147,
         914173108: 141,
         406632790: 142,
         150737169: 87,
         165179681: 40,
         112583212: 89,
         162228663: 52,
         162228665: 288,
         112583228: 101,
         112583231: 90,
         22986560: 117,
         23957570: 158,
         452934468: 270,
         23762376: 272,
         150736590: 50,
         150736591: 41,
         23795664: 54,
         150736593: 50,
         150636902: 53,
         159242472: 89,
         159242478: 79,
         150636917: 24,
         574537080: 267,
         158449760: 13,
         715575620: 164,
         305272357: 152,
         38569319: 4,
         97236426: 143,
         1058552716: 141,
         1058552715: 77,
         24226872: 128,
         715573881: 107,
         715573883: 157,
         150619005: 13,
         394382606: 210,
         344742073: 318,
         34662351: 364,
         23752172: 238,
         775131780: 82,
         961365515: 60,
         961365516: 64,
         97749774: 91,
         24454035: 14,
         24916901: 13,
         24732720: 69,
         99026996: 98,
         840458166: 5,
         24443831: 17,
         457205183: 7,
         24916807: 24,
         24916939: 6,
         755263202: 93,
         154442083: 31,
         755263203: 91,
         150636899: 56,
         154442086: 32,
         154442088: 22,
         154442089: 15,
         150636908: 63,
         154442093: 18,
         154442095: 47,
         150636912: 64,
         154442097: 27,
         154442099: 31,
         150636915: 57,
         154442101: 32,
         154442106: 44,
         150380280: 1,
         150380279: 1,
         223001539: 195,
         37122503: 4,
         993035145: 199,
         993035146: 195,
         23763977: 224,
         153797753: 56,
         153743386: 39,
         42288377: 104,
         684985752: 207,
         153743387: 59,
         153815349: 16,
         37691222: 25,
         23951161: 124,
         675698554: 72,
         153815355: 15,
         591045085: 131,
         23952131: 81,
         37246725: 59,
         49577096: 95,
         23854473: 95,
         163225636: 10,
         974477368: 33,
         1055765964: 37,
         1055765974: 43,
         24915419: 47,
         974959836: 47,
         99752050: 131,
         384230013: 103,
         384230014: 54,
         80562924: 13,
         31301718: 126,
         36997316: 14,
         25874854: 26,
         318406725: 6,
         85442152: 16,
         80412519: 9,
         75070824: 22,
         474147468: 18,
         744683666: 10,
         120555410: 10,
         120555411: 5,
         1059188633: 20,
         474125275: 16,
         974959837: 22,
         392773999: 48,
         23951767: 73,
         292214784: 28,
         393170561: 49,
         393170565: 26,
         30686213: 6,
         775556640: 32,
         392747170: 27,
         392747171: 29,
         392747172: 23,
         392747174: 25,
         232711079: 20,
         25578800: 59,
         657200050: 29,
         168546998: 71,
         118754615: 56,
         392740044: 32,
         86871008: 46,
         152149995: 17,
         392774002: 28,
         392774006: 29,
         393170550: 27,
         392774008: 32,
         392774011: 30,
         637644413: 4,
         637644414: 30,
         97749772: 233,
         38036655: 134,
         675698553: 217,
         693531866: 205,
         65254977: 68,
         574483650: 61,
         583331561: 67,
         23680878: 10,
         35209298: 81,
         308178203: 18,
         122270334: 69,
         65255007: 67,
         24443832: 6,
         25703475: 20,
         840458164: 38,
         24443830: 17,
         427200643: 12,
         142156865: 62,
         163858081: 30,
         163858051: 42,
         163858049: 24,
         142156869: 58,
         142156872: 85,
         163858090: 41,
         163858068: 43,
         974298132: 58,
         142156886: 65,
         142156857: 89,
         142156862: 85,
         239818732: 16,
         24771360: 255,
         198530824: 191,
         223006673: 139,
         23066740: 250,
         177180084: 244,
         23854595: 55,
         916003336: 20,
         134078882: 12,
         134078886: 25,
         80411559: 14,
         150886570: 78,
         24728630: 56,
         150886583: 58,
         150886594: 79,
         483221956: 14,
         483221972: 71,
         483221975: 78,
         150886615: 72,
         483221979: 43,
         150886628: 72,
         150886632: 78,
         81349739: 41,
         81349740: 41,
         775131779: 25,
         24772515: 67,
         83522693: 22,
         153840008: 38,
         406455413: 25,
         840458165: 27,
         777261239: 6,
         130316278: 25,
         24443833: 9,
         30789850: 47,
         78461185: 7,
         24915719: 57,
         24915721: 56,
         75689906: 7,
         809813947: 56,
         694821438: 7,
         694821439: 7,
         686651601: 66,
         37838548: 67,
         159483860: 6,
         662831987: 9,
         23951099: 60,
         689152192: 165,
         48769827: 158,
         23795565: 157,
         23795568: 189,
         156538834: 12,
         23795538: 158,
         37956149: 108,
         75999442: 51,
         746208777: 105,
         24915969: 19,
         36904808: 20,
         156608053: 41,
         156608055: 40,
         156608057: 40,
         156608061: 26,
         38531807: 21,
         23951237: 14,
         86164967: 10,
         222747882: 9,
         24581835: 16,
         133370606: 26,
         68286126: 26,
         936412753: 29,
         657982035: 15,
         155428148: 23,
         24479479: 86,
         215030168: 8,
         227756252: 67,
         97251488: 19,
         483738720: 4,
         915478220: 5,
         775100847: 3,
         116455319: 26,
         693546737: 2,
         693546738: 1,
         97251475: 4,
         693546740: 4,
         775100852: 13,
         32059922: 16,
         571994487: 10,
         24054420: 19,
         116455320: 19,
         915587813: 3,
         32059928: 10,
         122602438: 42,
         24443814: 40,
         23751867: 131,
         238939334: 27,
         591407235: 44,
         394382608: 14,
         24732721: 71,
         37134282: 165,
         275318479: 20,
         97236445: 75,
         239818741: 66,
         239818742: 69,
         24755840: 104,
         73711330: 48,
         532908004: 57,
         694351845: 20,
         631358429: 68,
         23951872: 31,
         23951874: 56,
         151869460: 13,
         151869462: 12,
         777242651: 11,
         151869468: 3,
         775556638: 55,
         775556639: 102,
         151869473: 4,
         151869474: 14,
         685828130: 3,
         151869477: 3,
         974477366: 33,
         299135044: 8,
         23854201: 9,
         27625596: 2,
         23994565: 9,
         97111248: 15,
         789620434: 4,
         395046101: 11,
         150886623: 31,
         395046130: 10,
         130644259: 20,
         23951662: 8,
         426033982: 9,
         528754495: 1,
         426033984: 12,
         528754505: 2,
         571994481: 9,
         571994482: 12,
         23951769: 12,
         483221928: 10,
         483221929: 10,
         483221935: 3,
         150898097: 5,
         150898101: 3,
         483221942: 5,
         150898103: 11,
         483221945: 8,
         483221946: 31,
         150898106: 4,
         150898107: 3,
         483221948: 3,
         483221949: 35,
         483221950: 9,
         150898112: 5,
         483221947: 34,
         150898115: 3,
         83738055: 3,
         483221966: 48,
         483221968: 45,
         483221970: 45,
         990948259: 2,
         150636910: 46,
         150636911: 63,
         675490033: 7,
         840458162: 23,
         686651602: 15,
         686640341: 90,
         406455411: 9,
         24917678: 297,
         689152193: 303,
         122602437: 170,
         23763916: 173,
         24443786: 42,
         24161870: 104,
         24161871: 78,
         692614930: 104,
         67624761: 92,
         213521410: 317,
         110057082: 133,
         283010968: 90,
         141265569: 103,
         141265570: 90,
         232711077: 16,
         23794856: 99,
         24443816: 339,
         177180085: 101,
         452934454: 308,
         452934453: 318,
         213521402: 437,
         591407234: 18,
         248940424: 32,
         97121839: 68,
         97251509: 82,
         222540727: 46,
         37691320: 21,
         150736588: 37,
         150736589: 65,
         37016911: 34,
         150736592: 35,
         1057256026: 41,
         150636905: 56,
         752730097: 53,
         752730098: 56,
         150636916: 54,
         150636913: 55,
         240092038: 94,
         24802988: 71,
         823407788: 77,
         240108147: 41,
         84690452: 111,
         84690455: 68,
         308178197: 74,
         308178198: 80,
         24479576: 61,
         24202637: 162,
         162228660: 240,
         24161653: 19,
         23854594: 126,
         23952132: 96,
         97111253: 62,
         49577052: 108,
         23854591: 131,
         195617230: 6,
         345757295: 2,
         116029578: 29,
         203885547: 22,
         127209004: 5,
         24915407: 21,
         185489812: 7,
         185489811: 5,
         227385305: 61,
         149811073: 126,
         24909193: 147,
         23763869: 127,
         24771362: 149,
         83738067: 77,
         43760621: 203,
         163832950: 16,
         198530825: 211,
         78785835: 151,
         24917570: 149,
         78785864: 164,
         37482523: 11,
         307255803: 40,
         223006672: 57,
         227385303: 44,
         227385308: 39,
         284468073: 9,
         284468075: 12,
         284468077: 9,
         307255805: 37,
         840833034: 55,
         112583221: 55,
         692034717: 49,
         308335488: 82,
         23763170: 105,
         109372547: 82,
         574541250: 144,
         24443793: 61,
         118296626: 116,
         109581299: 66,
         109372496: 84,
         23762032: 126,
         684985753: 68,
         23234597: 29,
         306342330: 12,
         150898114: 72,
         83738063: 72,
         83738064: 82,
         97111275: 95,
         24479477: 102,
         248940430: 11,
         248940433: 1,
         248940436: 18,
         838173996: 28,
         24443823: 72,
         24443824: 98,
         24443825: 127,
         97251505: 49,
         307105207: 29,
         30686779: 27,
         275318472: 1,
         275318473: 1,
         307252688: 6,
         306792403: 71,
         275318484: 1,
         86867171: 45,
         306097130: 84,
         306097131: 85,
         53198081: 7,
         1023950739: 4,
         1023950740: 3,
         23795654: 84,
         305217107: 4,
         825129833: 4,
         838173997: 26,
         758183648: 151,
         406632784: 32,
         406632785: 65,
         117978740: 32,
         80410758: 16,
         150886624: 42,
         150886634: 34,
         657209637: 50,
         80767307: 78,
         406632786: 33,
         37122586: 33,
         253246201: 33,
         151869466: 22,
         37112956: 45,
         675781468: 125,
         163391869: 153,
         163391870: 127,
         222749669: 61,
         240092041: 82,
         936412748: 66,
         936412749: 67,
         84690454: 61,
         37937066: 21,
         693531853: 162,
         723765198: 143,
         723765197: 91,
         693531859: 63,
         239994668: 35,
         122270319: 8,
         24915506: 41,
         174142869: 2,
         574537083: 44,
         483222000: 3,
         37688371: 9,
         571994467: 16,
         78461189: 22,
         755263212: 18,
         97236444: 48,
         712328843: 51,
         24443789: 88,
         97251496: 149,
         306718695: 68,
         669394539: 108,
         669394540: 104,
         669394541: 107,
         1054347499: 66,
         1054347500: 62,
         715573880: 51,
         697308513: 4,
         697308514: 4,
         777291969: 9,
         163858084: 10,
         991646983: 6,
         36867850: 33,
         684989324: 11,
         118775761: 10,
         163858101: 1,
         24435189: 3,
         24435190: 6,
         24581558: 8,
         163858073: 5,
         766366037: 11,
         163858075: 5,
         777291965: 3,
         308335486: 119,
         777252610: 67,
         24400261: 44,
         846938951: 17,
         322476202: 23,
         305538444: 35,
         24392333: 43,
         97251502: 57,
         24389744: 30,
         24389746: 68,
         24389747: 67,
         1057256029: 58,
         34663330: 149,
         194492785: 173,
         37015240: 23,
         24916400: 9,
         96889363: 17,
         77356699: 9,
         77356701: 7,
         305272358: 71,
         24054398: 86,
         153939404: 11,
         24443821: 46,
         24443822: 14,
         452934457: 31,
         307993861: 22,
         80375824: 39,
         75091546: 3,
         252536217: 2,
         532907982: 2,
         239981370: 56,
         24915618: 93,
         36881548: 8,
         318408391: 15,
         195617232: 1,
         195617233: 1,
         51764176: 11,
         51764178: 62,
         81641184: 1,
         127359457: 2,
         75070821: 1,
         838173995: 59,
         112583224: 98,
         150636909: 136,
         82479086: 79,
         307279424: 9,
         809813948: 10,
         163858078: 26,
         24772513: 159,

_________________________________
Test Overpass API

In [157]:
import overpy
api = overpy.Overpass()
result = api.query("""[out:json];
                    way(170076129);
                    out geom;""")

In [162]:
len(result.ways), result.ways, result.ways[0].get_nodes(resolve_missing=True)

(1,
 [<overpy.Way id=170076129 nodes=[907823976, 907823963, 907823962, 4786649726, 1271454530, 907823964, 907823975, 907823965]>],
 [<overpy.Node id=907823976 lat=46.0940056 lon=11.1180917>,
  <overpy.Node id=907823963 lat=46.0940201 lon=11.1180161>,
  <overpy.Node id=907823962 lat=46.0940662 lon=11.1179733>,
  <overpy.Node id=4786649726 lat=46.0945524 lon=11.1177386>,
  <overpy.Node id=1271454530 lat=46.0950002 lon=11.1174901>,
  <overpy.Node id=907823964 lat=46.0950538 lon=11.1174607>,
  <overpy.Node id=907823975 lat=46.0951031 lon=11.1174639>,
  <overpy.Node id=907823965 lat=46.0951444 lon=11.1175226>])

In [165]:
result.ways[0].get_nodes(resolve_missing=True)[0].lat

Decimal('46.0940056')

End Test

_________________________________

In [44]:
# ask for all way ids in a single request to avoid OverpassTooManyRequests error
els = 'id: '
for el in c.keys():
    els = els + str(el) +', '
els = els[:-2] # string of way ids to pass to request coordinates

# using overpy:
# api = overpy.Overpass()
# result = api.query("""[out:json];
#                     way("""+str(els)+""");
#                     out geom;""")

# using Overpass Docker API:
# https://github.com/wiktorn/Overpass-API

url = 'http://localhost:12345/api/interpreter'
data = 'data=way('+str(els)+');out geom;'
r = requests.post(url, data=data)
root = ET.fromstring(r.text)

nodes_coords = []
waysids = []
for child in root:
    if child.tag == 'way':
        waysids.append(int(child.attrib['id']))
        nodes=[]
        for node in child:
            if node.tag == 'nd':
                # print(node.attrib['ref']) # node id
                nodes.append([float(node.attrib['lat']), float(node.attrib['lon'])])
        nodes_coords.append(nodes)

In [45]:
cnt=[]
for id in waysids:
    cnt.append(c[id])

In [46]:
ways = pd.DataFrame({'way_id': waysids, 'route': nodes_coords, 'freq': cnt})
ways

          way_id                                              route  freq
0       22986084  [[46.0666524, 11.1190333], [46.0666403, 11.118...   349
1       22986312  [[46.0674662, 11.1266008], [46.0675156, 11.126...   190
2       22986560  [[46.069021, 11.1225351], [46.0693306, 11.1224...   117
3       23056771  [[46.0969958, 11.1125195], [46.096235, 11.1127...     5
4       23058066  [[46.0838565, 11.1146839], [46.0839814, 11.114...    19
...          ...                                                ...   ...
2487  1058552722  [[46.097594, 11.1024637], [46.0973823, 11.1026...     1
2488  1058552723  [[46.1010479, 11.1017295], [46.1009174, 11.101...     2
2489  1059033164  [[46.0996549, 11.117578], [46.099468, 11.11766...     3
2490  1059175213  [[46.058549, 11.1227312], [46.0585422, 11.1227...    49
2491  1059188633  [[46.0928535, 11.1151339], [46.0929237, 11.115...    20

[2492 rows x 3 columns]

In [100]:
text_html = '''
{% macro html(this, kwargs) %}
<div style="
    position: fixed; 
    top: 50px;
    right: 10px;
    width: 360px;
    height: 50px; 
    z-index:9998;
    font-size:14px;
    ">
    <p style="color:white;font-size:90%;margin-right:10px;">Number of times the segment was passed through</p>
</div>
{% endmacro %}
'''

In [103]:
f_map = folium.Map(location=[46.066,11.133], tiles='cartodbdark_matter', zoom_start=14) #  tiles="cartodbdark_matter" "Stamen Toner" "OpenStreetMap"


colormap = cm.LinearColormap(colors=['cyan', 'yellow', 'orange', 'red'], # ['darkblue', 'blue', 'cyan', 'yellow', 'orange', 'red']
                            index = np.linspace(min(c.values()), max(c.values()), num=4),
                            vmin = min(c.values()), vmax = max(c.values()) ) # caption='Number of times the segment was passed through'

text = folium.MacroElement().add_to(f_map) 
text._template = branca.element.Template(text_html)

fg = folium.FeatureGroup(name='overpass_tratte_forti')    


for i in range(len(ways)): 
    # fg = folium.FeatureGroup(name=str(df.month[i])) # a feature group for each month
    color = colormap(c[ways.way_id[i]])
    w = min(ways['freq'][i]/100 , 5)
    folium.vector_layers.PolyLine(ways.route[i], color=color, weight=w).add_to(fg)


f_map.add_child(fg)
f_map.add_child(colormap)

f_map.save('html/overpass_tratte_forti.html')

### Heatmap by hour of a given day

In [ ]:
df = pd.read_parquet("../data/trips_pointv3_cleaned.parquet")
df.point_latitude = df.point_latitude.astype(float)
df.point_longitude = df.point_longitude.astype(float)
df['date'] = pd.to_datetime(df.date)
df['hour'] = df['point_timestamp'].dt.hour

In [ ]:
# select one day
df = df[df.date == pd.Timestamp(2022, 1, 31)]

In [ ]:
lat_long_list = []
for i in range(1,25): 
    temp=[]
    for index, instance in df[df['hour'] == i].iterrows():
        temp.append([instance['point_latitude'],instance['point_longitude']])
    lat_long_list.append(temp)

In [ ]:
import folium
from folium.plugins import HeatMapWithTime
from branca.element import Figure

fig = Figure(width=850, height=550)
m = folium.Map(location=[46.06, 11.13], zoom_start=12, control_scale=True)
fig.add_child(m)
HeatMapWithTime(lat_long_list, radius=5, auto_play=True, position='bottomright').add_to(m)
m.save('heatmap_by_hour.html')

### Heatmap through a month

In [ ]:
df = pd.read_parquet("../data/trips_pointv3_cleaned.parquet")
df.point_latitude = df.point_latitude.astype(float)
df.point_longitude = df.point_longitude.astype(float)
df['date'] = pd.to_datetime(df.date)
df['hour'] = df['point_timestamp'].dt.hour

In [ ]:
# select month
df['month'] = df['point_timestamp'].dt.month
df['year'] = df['point_timestamp'].dt.year
df = df[df.month == 2]
df = df[df.year == 2022]

In [ ]:
lat_long_list = []
for i in df['point_timestamp'].unique():
    temp=[]
    for index, instance in df[df['point_timestamp'] == i].iterrows():
        temp.append([instance['point_latitude'],instance['point_longitude']])
    lat_long_list.append(temp)

In [ ]:
# time indexes for map
time_index = []
for i in df['point_timestamp'].unique():
    time_index.append(i)

date_strings = [d.strftime('%d/%m/%Y, %H:%M:%S') for d in time_index]

In [ ]:
m = folium.Map(location=[46.06, 11.13], zoom_start = 12, control_scale=True)
HeatMapWithTime(lat_long_list, radius=5, auto_play=True, position='bottomright', name="cluster", index = date_strings, max_opacity=0.7).add_to(m)

m.save('heatmap_month.html')